### ISSUE TITLE
How to send order confirmation email?

### ISSUE THREAD

**Issue by lfurzewaddock** [OShop/OShop#10]
I cannot find a way to send a confirmation email, which includes all the details of an order.

I tested a new workflow starting with 'Content Created', type 'Order' linked to an email. I used the customer address tokens, but did not find other relevant tokens in the UI picker. 

The email did arrive after a test transaction, but did not contain any values.

When we find a solution I will add it to the wiki.

**Comment by TFleury** [comment]
It's not implemented yet.

**Comment by lfurzewaddock** [comment]
OK, it helps to know it's not available, rather than something I've missed.

Another enhancement, would be a secure customer area, like 'My Account'. I'll open another issue, so you/or anyone else can comment.

**Comment by TFleury** [comment]
> Another enhancement, would be a secure customer area, like 'My Account'. I'll open another issue, so you/or anyone else can comment.

You should find a basic Customer area at /OShop/Customer

**Comment by lfurzewaddock** [comment]
Ah great! - It does nearly everything it could do except let them change their email.

More testing and wikis.

**Comment by TFleury** [comment]
I just added Order Activities feature and some order and customer related tokens. (See 4125c2c614e7aee165a7dac39102a0c75f0d160a)

You can now notify your customers.
