### ISSUE TITLE
Import the module in to Orchard.Source

### ISSUE THREAD

**Issue by jhallam3** [OShop/OShop#14]
Hi there, 

Im the orchard.source version of Orchard and cant get your module to be added. 

Ive added it in to modules and rebuilt. is that all is needed?

**Comment by jhallam3** [comment]
thats modules directory in the root of the orchard.source folder.

**Comment by TFleury** [comment]
Once you have added oshop to your modules directory, you should be able to enable features you need.

There is few documentation on [wiki pages](/OShop/OShop/wiki)
