### ISSUE TITLE
What does the zone do?

### ISSUE THREAD

**Issue by ahmadidev** [OShop/OShop#15]
I created a shipping provider but in Checkout step the shipping method dropdown is empty. I traced how the shipping list is build and I figured out that `OShop.Services.ShippingService.GetSuitableOption` relies on zone parameter which is null.
So, what does the zone in shipping?

**Comment by TFleury** [comment]
Zones are groups of country/state You have to create a least one (geographical) zone.
When you create a shipping provider, you can then create `ShippingOptions` which are bound to a zone.
When you are in checkout, you can chose a `ShippingProvider` available for your zone (based on selected country/state).
