### ISSUE TITLE
Missing information on ValidateOrder page

### ISSUE THREAD

**Issue by lfurzewaddock** [OShop/OShop#4]
**Missing information:** 
- Billing address
- Order number
- Order details including;
  - SKU
  - Product name/description
  - Quantity
  - Price

_Note: The correct VAT amount is present_
### Steps to recreate:

**1) Add product to shopping cart.
2) Visit shopping cart page**

_~/OShop/ShoppingCart_

Empty cart [link]

| Product | Unit Price | Qty |  | Total |
| --- | --- | --- | --- | --- |
| Test product 1 | £12.00 | 1 | Remove [button] | £12.00 |

Tuesday, June 23, 2015 2:11:03 PM

Test product 1 body more

Taxes   £2.00
Total   £12.00

**3) Click 'Checkout' button.**

_~/OShop/Checkout_

Your addresses :

Create new address [link]

| Billing address |  |  |
| --- | --- | --- |
| Alias of address selected [Select list] | Edit [button] | Remove [button] |

**4) Click 'Validate' button**

_~/OShop/Checkout/ValidateOrder_

Order

Customer :

First name : FName
Last name : LName
E-mail :

Billing Address :

Draft Order number : Order status : Pending

|  | SKU | Product | Unit Price | Qty. | Total |
| --- | --- | --- | --- | --- | --- |
| VAT |  |  |  |  | £2.00 |
| Order total |  |  |  |  | £2.00 |

**NO ERRORS LOGGED**

**Comment by TFleury** [comment]
There are different things :
- Billing address :
  - Are there some country created ?
  - Did you select a country in you CustomerAddress ?
  - You have to fill address format for each country created, otherwise OShop can't display it (missing some documentation)
    Here is a sample for UK :

```
{OrderAddress.Company}
{OrderAddress.FirstName} {OrderAddress.LastName}
{OrderAddress.Address1}
{OrderAddress.Address2}
{OrderAddress.City}
{OrderAddress.Zipcode}
```
- Order number : order is created after validation, thus order number is empty at validation step

I can't reproduce missing order details right now, keep searching...

**Comment by lfurzewaddock** [comment]
- Billing address
  - 1 x country created and 1 x state created
  - Yes, 1 x country is selected for the test customer address, forced by app validation
  - **Thank you**: I have used the following address format and it now appears as expected.

```
{OrderAddress.Company}
{OrderAddress.FirstName} {OrderAddress.LastName}
{OrderAddress.Address1}
{OrderAddress.Address2}
{OrderAddress.City}
{OrderAddress.State}
{OrderAddress.Zipcode}
{OrderAddress.Country}
```

Test address in use;

Co. Name 5
FirstName5 LastName5
Adr line 1
Adr line 2
AdrCity5
Kent
Adr zip code 5
United Kingdom
- Order number: OK, I suggest hiding it in ~/OShop/Checkout/ValidateOrder page as it is not yet available.

**Comment by TFleury** [comment]
I reproduced order details missing, it was caused by mistmatch in my migration, and I will fix it.

To fix your instance :
- Create a content part named "OrderProductsPart"
- Attach this part to Order content type

**Comment by lfurzewaddock** [comment]
Great! Looks like everything is fixed: (See current information that is available below).

What do you think about hiding the order number at this stage?

_~/OShop/Checkout/ValidateOrder_

Order

Customer :

First name : FName
Last name : LName
E-mail :

Billing Address :

Co. Name 5
FirstName5 LastName5
Adr line 1
Adr line 2
AdrCity5
Kent
Adr zip code 5
United Kingdom

Draft Order number : Order status : Pending

|  | SKU | Product | Unit Price | Qty. | Total |
| --- | --- | --- | --- | --- | --- |
|  | TP | Test product 1 | £10.00 | 1 | £10.00 |
| Products total |  |  |  |  | £10.00 |
| VAT |  |  |  |  | £2.00 |
| Order total |  |  |  |  | £12.00 |
