### ISSUE TITLE
State drop down list and / or all location fields are missing from shopping cart form

### ISSUE THREAD

**Issue by lfurzewaddock** [OShop/OShop#6]
### Steps to recreate:

**1) Sign in with default admin account.
2) Visit shopping cart page.
3) Click the 'Empty cart' link.
4) Add product to shopping cart. _(product does NOT require shipping)_
5) Visit shopping cart page.**

_~/OShop/ShoppingCart_

Empty cart [link]

| Product | Unit Price | Qty |  | Total |
| --- | --- | --- | --- | --- |
| Test product 1 | £12.00 | 1 | Remove [button] | £12.00 |

Tuesday, June 23, 2015 2:11:03 PM

Test product 1 body more

Taxes   £2.00
Total   £12.00

Location 

Select your location to estimate taxes and shipping.

Country
 [drop down list] 

Update [button]

Checkout [button]

**6) Click 'Update' button.**

State
 [drop down list] 

Appears between the Country drop down list and the 'Update' button.

**Observation**: This issue (whether the state drop down list is visible or not) does note prevent users from proceeding to the next stage by clicking the 'Checkout' button, or removing the item by clicking the 'Remove' button.

**7) Click 'Checkout' button.**

~/OShop/Checkout

**8) Click 'Return' button.**

**Observation**: The 'Location' section for the shopping cart is completely missing. 

_~/OShop/ShoppingCart_

Empty cart [link]

| Product | Unit Price | Qty |  | Total |
| --- | --- | --- | --- | --- |
| Test product 1 | £12.00 | 1 | Remove [button] | £12.00 |

Tuesday, June 23, 2015 2:11:03 PM

Test product 1 body more

Taxes   £2.00
Total   £12.00

Update [button]

Checkout [button]

**9) Click 'Update' button.**

**Observation**: The 'Location' section is still completely missing, but the cart does update as expected without errors.

**Comment by TFleury** [comment]
It's an expected behavior : once you selected a billing address (and optionaly a shipping address), taxes and shipping amount are based on these locations. Location selector is then hidden.

I thought it made sense... don't you ?

**Comment by lfurzewaddock** [comment]
Yes, true that does make sense if the user is logged in and they have existing address details, although they may want to change the delivery to another address (if applicable).

Its also odd though that the state drop down list only appears when the 'Update' button is pressed.

Would it not be easier to always show the Locations selector with both the Country and State drop down lists visible? If an existing user is logged in, the state and country drop down lists are automatically selected. This would allow them to make a change if they decide to send a gift to another state and/or country for example.

However if a user has several addresses, I'm not sure how you decide which one to use, if they are not marked as default? Perhaps the first address should always be marked as default. Therefore you would remove/disable the 'Set as default address' check box in the create new address form for new users?

What do you think?

**Comment by TFleury** [comment]
> Yes, true that does make sense if the user is logged in and they have existing address details, although they may want to change the delivery to another address (if applicable).

Customer can create multiple addresses, taxes and shipping are based on selected addresses.

> Its also odd though that the state drop down list only appears when the 'Update' button is pressed.

Fixed with #7 

> Would it not be easier to always show the Locations selector with both the Country and State drop down lists visible? If an existing user is logged in, the state and country drop down lists are automatically selected. This would allow them to make a change if they decide to send a gift to another state and/or country for example.

Requires rewriting some routines... Don't know if it's worth it.

**Comment by lfurzewaddock** [comment]
OK, no problem, leave it for now. 

I'll know more about how the the system works and will be in a better position to offer new ideas after I've done some more testing, especially with new customer accounts.

I've started on a wiki for the OShop.PayPal module, but need to finish the testing stage [https://github.com/lfurzewaddock/OShop.PayPal/wiki](https://github.com/lfurzewaddock/OShop.PayPal/wiki) I'm pretty sure I can upload it to the main project wiki if you're happy with it. Make any changes or comments you like.

**Comment by TFleury** [comment]
Very good job, feel free to publish it to the main project.

**Comment by lfurzewaddock** [comment]
OK, will do.
